language: python
cache: pip
python:
  - '3.7'
install:
  - pip install .
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: emorynlp
  password:
    secure: SNFcPZ+zWngEYMkkWbyu97fJZxlZfMOh2n32WeFbHUNrt6/KJKb6B5KR2dU4HxIzUrITlMxhhqBdelYaDlGwd3SeIYTyaMH4d2S5I5LQEmo99slVi/MTqewr+EJyM0rCkj05O3/jpWVkQtASITzpZGGdQhX2JluwoKZPYmPVtkrv0Vi+1h7Rf9LQGWKrG5jikwG4/VkT+Wf/jKOauoMTSlev5XaPkIh1Ww0IxmF1xG4c63EBCkt2I3+h0Q9Y1lFoqeeabqgKjFJsnZHs8qA8MsskJWpFRSWNpcBxAOEQcMPoY7qCn2fFCTZYszmui7/BseEuGfls33oJ+ys+bFuEoXobqq+BVF3GxagIO0tej0TYcs+SacBE2HUqWJmegr56MaeRArq1i4PWH+cdBG5S1gzaJ85WjUhP3LNUVttit5IXLc+uIecL4ZlEh7V0apJp+bv0g5fEAV+szKnfSuLm/ZDttxMvml5n/ao9DO9HHcfaY5DGKUxfrjAItqdO21TwpCMdCNu+cijJKQGjO47zNZDdyqS2oih5my4bFYhyRB69ts3VOTGnwC/zP6gDVAZIg+Enco4dSKP4mGF0eHOr9z4kQGNOGXAlvVT/O7rLTZHbg4vy2NmvNxvdRrAMDBt5O37GauhTiA5XVv1TLaXayH8v18XElvEJqdw2/xHhSi0=
  on:
    python: 3.7
    branch: main
script:
  - python tests/test_joint_model.py
notifications:
  email: false
